require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WeblocationsController do

  # This should return the minimal set of attributes required to create a valid
  # Weblocation. As you add validations to Weblocation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WeblocationsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all weblocations as @weblocations" do
      weblocation = Weblocation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:weblocations).should eq([weblocation])
    end
  end

  describe "GET show" do
    it "assigns the requested weblocation as @weblocation" do
      weblocation = Weblocation.create! valid_attributes
      get :show, {:id => weblocation.to_param}, valid_session
      assigns(:weblocation).should eq(weblocation)
    end
  end

  describe "GET new" do
    it "assigns a new weblocation as @weblocation" do
      get :new, {}, valid_session
      assigns(:weblocation).should be_a_new(Weblocation)
    end
  end

  describe "GET edit" do
    it "assigns the requested weblocation as @weblocation" do
      weblocation = Weblocation.create! valid_attributes
      get :edit, {:id => weblocation.to_param}, valid_session
      assigns(:weblocation).should eq(weblocation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Weblocation" do
        expect {
          post :create, {:weblocation => valid_attributes}, valid_session
        }.to change(Weblocation, :count).by(1)
      end

      it "assigns a newly created weblocation as @weblocation" do
        post :create, {:weblocation => valid_attributes}, valid_session
        assigns(:weblocation).should be_a(Weblocation)
        assigns(:weblocation).should be_persisted
      end

      it "redirects to the created weblocation" do
        post :create, {:weblocation => valid_attributes}, valid_session
        response.should redirect_to(Weblocation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved weblocation as @weblocation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Weblocation.any_instance.stub(:save).and_return(false)
        post :create, {:weblocation => {}}, valid_session
        assigns(:weblocation).should be_a_new(Weblocation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Weblocation.any_instance.stub(:save).and_return(false)
        post :create, {:weblocation => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested weblocation" do
        weblocation = Weblocation.create! valid_attributes
        # Assuming there are no other weblocations in the database, this
        # specifies that the Weblocation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Weblocation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => weblocation.to_param, :weblocation => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested weblocation as @weblocation" do
        weblocation = Weblocation.create! valid_attributes
        put :update, {:id => weblocation.to_param, :weblocation => valid_attributes}, valid_session
        assigns(:weblocation).should eq(weblocation)
      end

      it "redirects to the weblocation" do
        weblocation = Weblocation.create! valid_attributes
        put :update, {:id => weblocation.to_param, :weblocation => valid_attributes}, valid_session
        response.should redirect_to(weblocation)
      end
    end

    describe "with invalid params" do
      it "assigns the weblocation as @weblocation" do
        weblocation = Weblocation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Weblocation.any_instance.stub(:save).and_return(false)
        put :update, {:id => weblocation.to_param, :weblocation => {}}, valid_session
        assigns(:weblocation).should eq(weblocation)
      end

      it "re-renders the 'edit' template" do
        weblocation = Weblocation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Weblocation.any_instance.stub(:save).and_return(false)
        put :update, {:id => weblocation.to_param, :weblocation => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested weblocation" do
      weblocation = Weblocation.create! valid_attributes
      expect {
        delete :destroy, {:id => weblocation.to_param}, valid_session
      }.to change(Weblocation, :count).by(-1)
    end

    it "redirects to the weblocations list" do
      weblocation = Weblocation.create! valid_attributes
      delete :destroy, {:id => weblocation.to_param}, valid_session
      response.should redirect_to(weblocations_url)
    end
  end

end
